DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

notice/urls.py
from django.urls import path, include
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

sskUser/urls.py
from django.urls import path
from . import views

app_name = 'sskUser'

# http://127.0.0.1:8000/account/img_captcha   xxxxx

urlpatterns = [
    path('', views.user_info, name='index'),
    path('login/', views.user_login, name='login'),
    path('register/', views.user_register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('delete/', views.user_delete, name='delete'),
    path('resetpwd/', views.user_resetpwd, name='resetpwd'),
    # 图形验证码
    path('img_captcha/', views.img_captcha, name='img_captcha'),
]

sunBlog3/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

from article import views
import notifications.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('download/', views.download, name='download'),
    path('article/', include('article.urls')),

    path('s/', views.article_search,name='search'),
    path('taglist/', views.article_taglist),
    path('ueditor/', include('DjangoUeditor.urls')),
    re_path('^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    path('comment/', include('comment.urls', namespace='comment')),
    path('account/', include('sskUser.urls', namespace='user')),
    path('accounts/', include('allauth.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
]

templates/user/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<title>用户中心-全栈记事交流博客</title>
<link rel="icon" href="favicon.ico" type="image/ico">
<meta name="keywords" content="LightYear,光年,后台模板,后台管理系统,光年HTML模板">
<meta name="description" content="LightYear是一个基于Bootstrap v3.3.7的后台管理系统的HTML模板。">
<meta name="author" content="yinqi">
    <link rel="icon" href="http://www.tkv5.cn/zb_users/theme/tpure/style/images/favicon.ico"/>
<link rel="stylesheet" rev="stylesheet" href="http://www.tkv5.cn/zb_users/plugin/YtUser/template/css/fonts/iconfont.css" type="text/css" media="all" />
<link rel="stylesheet" rev="stylesheet" href="http://www.tkv5.cn/zb_users/plugin/YtUser/template/css/txcstx.css" type="text/css" media="all" />
<link rel="stylesheet" rev="stylesheet" href="http://www.tkv5.cn/zb_users/plugin/YtUser/template/css/style2.css" type="text/css" media="all" />
<script src="http://www.tkv5.cn/zb_system/script/jquery-2.2.4.min.js" type="text/javascript"></script>
<script src="http://www.tkv5.cn/zb_system/script/zblogphp.js" type="text/javascript"></script>
<script src="http://www.tkv5.cn/zb_system/script/c_html_js_add.php" type="text/javascript"></script>
<script src="http://www.tkv5.cn/zb_users/plugin/YtUser/template/js/jquery-labelauty.js" type="text/javascript"></script>
<link href="http://www.tkv5.cn/zb_users/plugin/YtUser/template/css/bootstrap.min.css" rel="stylesheet">
<link href="http://www.tkv5.cn/zb_users/plugin/YtUser/template/css/materialdesignicons.min.css" rel="stylesheet">
<link href="http://www.tkv5.cn/zb_users/plugin/YtUser/template/css/style.min.css" rel="stylesheet">
<link href="http://www.tkv5.cn/zb_users/plugin/fancybox/fancybox.css" rel="stylesheet" type="text/css" />

<script src="http://www.tkv5.cn/zb_users/plugin/fancybox/fancybox.js"></script>
<script type="text/javascript">$(document).ready(function() {$(".fancybox").fancybox();});</script>
<script src="http://www.tkv5.cn/zb_users/plugin/YtUser/js/ytjs.php" type="text/javascript"></script>
<script src="http://www.tkv5.cn/zb_users/plugin/YtUser/js/layui/layui.all.js" type="text/javascript"></script>
</head>
<body data-logobg="color_5" data-headerbg="default" data-sidebarbg="color_8" data-theme="default">
<div class="lyear-layout-web">
  <div class="lyear-layout-container">
    <!--左侧导航-->
    <aside class="lyear-layout-sidebar">
      <!-- logo -->
      <div id="logo" class="sidebar-header">
        <a href="http://www.tkv5.cn/"><img src="http://www.tkv5.cn/zb_users/plugin/YtUser/template/images/logo-sidebar.png" title="LightYear" alt="LightYear" /></a>
      </div>
      <div class="lyear-layout-sidebar-scroll"> 
        
        <nav class="sidebar-main">
          <ul class="nav nav-drawer">
            
<li class="nav-item"> <a href="http://www.tkv5.cn/user/User.html"><i class="mdi mdi-home"></i> 后台首页</a> </li>
<li class="nav-item nav-item-has-subnav">
    <a href="javascript:void(0)"><i class="mdi mdi-file-outline"></i> 用户管理</a>
    <ul class="nav nav-subnav">
    <li><a href="http://www.tkv5.cn/">修改资料</a></li>
    <li><a href="http://www.tkv5.cn/user/Changepassword.html">修改密码</a></li>
    <li><a href="http://www.tkv5.cn/user/Commentlist">评论管理</a></li>
    <li><a href="http://www.tkv5.cn/user/Favorite">我的收藏</a></li>
    </ul>
</li>
<li class="nav-item nav-item-has-subnav">
    <a href="javascript:void(0)"><i class="mdi mdi-palette"></i>文章管理</a>
    <ul class="nav nav-subnav">
    <li><a href="http://www.tkv5.cn/user/Articlelist">文章管理</a></li>
        
    </ul>
</li>
<li class="nav-item nav-item-has-subnav">
    <a href="javascript:void(0)"><i class="mdi mdi-format-align-justify"></i> 积分充值</a>
    <ul class="nav nav-subnav">
    <li><a href="http://www.tkv5.cn/user/Integral.html">积分充值</a></li>
    <li><a href="http://www.tkv5.cn/user/Upgrade.html">VIP充值</a></li>
    <li><a href="http://www.tkv5.cn/user/Paylist">购买列表</a></li>
    <li><a href="http://www.tkv5.cn/user/Consume">消费记录</a></li>
    </ul>
</li>


          </ul>
        </nav>
      </div>
    </aside>
    <!--End 左侧导航-->
    
    <!--头部信息-->
    <header class="lyear-layout-header">
      
      <nav class="navbar navbar-default">
        <div class="topbar">
          
          <div class="topbar-left">
            <div class="lyear-aside-toggler">
              <span class="lyear-toggler-bar"></span>
              <span class="lyear-toggler-bar"></span>
              <span class="lyear-toggler-bar"></span>
            </div>
            <span class="navbar-page-title"> 后台首页 </span>
          </div>
          
          <ul class="topbar-right">
            <li class="dropdown dropdown-profile">
              <a href="javascript:void(0)" data-toggle="dropdown">
                <img class="img-avatar img-avatar-48 m-r-10" src="http://www.tkv5.cn/zb_users/plugin/YtUser/template/images/users/avatar.jpg" alt="yeyuge" />
                <span>{{ user.username }}<span class="caret"></span></span>
              </a>
              <ul class="dropdown-menu dropdown-menu-right">
                <li> <a href="http://www.tkv5.cn/"><i class="mdi mdi-account"></i> 个人信息</a> </li>
                <li> <a href="http://www.tkv5.cn/user/Changepassword.html"><i class="mdi mdi-lock-outline"></i> 修改密码</a> </li>
                <li class="divider"></li>
                <li> <a href="{% url 'sskUser:logout' %}"><i class="mdi mdi-logout-variant"></i> 退出登录</a> </li>
              </ul>
            </li>
            <!--切换主题配色-->
          </ul>
          
        </div>
      </nav>
      
    </header>
    <!--End 头部信息-->
    <main class="lyear-layout-content">
      <div class="container-fluid">    
   


<div class="row">
          <div class="col-sm-6 col-lg-3">
            <div class="card bg-primary">
              <div class="card-body clearfix">
                <div class="pull-right">
                  <p class="h6 text-white m-t-0">账户余额</p>
                  <p class="h3 text-white m-b-0 fa-1-5x">0</p>
                </div>
                <div class="pull-left"> <span class="img-avatar img-avatar-48 bg-translucent"><i class="mdi mdi-currency-cny fa-1-5x"></i></span> </div>
              </div>
            </div>
          </div>
          
          <div class="col-sm-6 col-lg-3">
            <div class="card bg-danger">
              <div class="card-body clearfix">
                <div class="pull-right">
                  <p class="h6 text-white m-t-0">Vip会员</p>
                  <p class="h3 text-white m-b-0 fa-1-5x"> 否</p>
                </div>
                <div class="pull-left"> <span class="img-avatar img-avatar-48 bg-translucent"><i class="mdi mdi-account fa-1-5x"></i></span> </div>
              </div>
            </div>
          </div>
          
          <div class="col-sm-6 col-lg-3">
            <div class="card bg-success">
              <div class="card-body clearfix">
                <div class="pull-right">
                  <p class="h6 text-white m-t-0">全部评价</p>
                  <p class="h3 text-white m-b-0 fa-1-5x"> 3</p>
                </div>
                <div class="pull-left"> <span class="img-avatar img-avatar-48 bg-translucent"><i class="mdi mdi-arrow-down-bold fa-1-5x"></i></span> </div>
              </div>
            </div>
          </div>
          
          <div class="col-sm-6 col-lg-3">
            <div class="card bg-purple">
              <div class="card-body clearfix">
                <div class="pull-right">
                  <p class="h6 text-white m-t-0">全站文章</p>
                  <p class="h3 text-white m-b-0 fa-1-5x">0条</p>
                </div>
                <div class="pull-left"> <span class="img-avatar img-avatar-48 bg-translucent"><i class="mdi mdi-comment-outline fa-1-5x"></i></span> </div>
              </div>
            </div>
          </div>
        </div>
<div class="row">
    
    <div class="col-lg-12">
    <div class="card">
        <div class="card-header">
        <h4>最新文章</h4>
        </div>
        <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover">
            <thead>
                <tr>
                <th>标题</th>
                <th>作者</th>
                <th>阅读数</th>
                <th>发布日期</th>
                </tr>
            </thead>
            <tbody>
                            <tr>
                <td><a href="http://www.tkv5.cn/post/231.html">ps中常用的快捷键</td>
                <td>admin</td>
                <td>31</td>
                <td>2021-02-26</td>
              
                </tr>
                                <tr>
                <td><a href="http://www.tkv5.cn/post/230.html">eyoucms管理员密码修改教程。</td>
                <td>admin</td>
                <td>28</td>
                <td>2021-02-26</td>
              
                </tr>
                                <tr>
                <td><a href="http://www.tkv5.cn/post/229.html">最为一个牛破天的计算机程序员，必须掌握思维小亮点</td>
                <td>admin</td>
                <td>32</td>
                <td>2021-02-23</td>
              
                </tr>
                                <tr>
                <td><a href="http://www.tkv5.cn/post/228.html">（热）分享一款zblog免费主题</td>
                <td>admin</td>
                <td>62</td>
                <td>2021-01-26</td>
              
                </tr>
                                <tr>
                <td><a href="http://www.tkv5.cn/post/227.html">404页面分享</td>
                <td>admin</td>
                <td>109</td>
                <td>2021-01-03</td>
              
                </tr>
                                <tr>
                <td><a href="http://www.tkv5.cn/post/226.html">zblog内置的cookie调用代码</td>
                <td>admin</td>
                <td>164</td>
                <td>2020-12-18</td>
              
                </tr>
                                <tr>
                <td><a href="http://www.tkv5.cn/post/225.html">zblog相关文章功能调用代码</td>
                <td>admin</td>
                <td>150</td>
                <td>2020-12-18</td>
              
                </tr>
                                <tr>
                <td><a href="http://www.tkv5.cn/post/224.html">zblog调用本周热门、本月热门、本年热门文章的方法</td>
                <td>admin</td>
                <td>151</td>
                <td>2020-12-18</td>
              
                </tr>
                                <tr>
                <td><a href="http://www.tkv5.cn/post/223.html">zblog评论设置标签探讨</td>
                <td>admin</td>
                <td>108</td>
                <td>2020-12-18</td>
              
                </tr>
                            </tbody>
            </table>
        </div>
        </div>
    </div>
    </div>
</div>


</div>
</div>
<script type="text/javascript" src="http://www.tkv5.cn/zb_users/plugin/YtUser/template/js/bootstrap.min.js"></script>
<script type="text/javascript" src="http://www.tkv5.cn/zb_users/plugin/YtUser/template/js/perfect-scrollbar.min.js"></script>
<script type="text/javascript" src="http://www.tkv5.cn/zb_users/plugin/YtUser/template/js/main.min.js"></script>
<script  type="text/javascript" src="http://www.tkv5.cn/zb_users/plugin/YtUser/template/js/txcstx.js" type="text/javascript"></script>
<script type="text/javascript">
    var url=bloghost;
    url=url.substr(0,url.length-1)+"/user/User.html";
    $(".nav-item-has-subnav a").each(function(){
        if($(this).attr('href')==url)
        {
            $(this).parent("li").addClass("active").parents(".nav-item-has-subnav").addClass("active open")
        }
    })
	$(".verify").click(function(){
			$(".verify").attr('src',$(this).attr('src')+"?m="+Math.random())
		})
</script>
</body>
</html>

templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<title>登录页面</title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />

	<link rel="stylesheet" type="text/css" href="{% static 'login/vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/fonts/iconic/css/material-design-iconic-font.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'login/css/main.css' %}">
</head>

<body>

	<div class="limiter">
		<div class="container-login100" style="background-image: url('{% static "login/images/bg-01.jpg" %}');">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
				<form class="login100-form validate-form" method="post" action="{% url 'sskUser:login' %}">
                    {% csrf_token %}
					<span class="login100-form-title p-b-49">登录</span>

					<div class="wrap-input100 validate-input m-b-23" data-validate="请输入用户名">
						<span class="label-input100">用户名</span>
						<input class="input100" type="text" name="username" placeholder="请输入用户名" autocomplete="off">
						<span class="focus-input100" data-symbol="&#xf206;"></span>
					</div>

					<div class="wrap-input100 validate-input" data-validate="请输入密码">
						<span class="label-input100">密码</span>
						<input class="input100" type="password" name="password" placeholder="请输入密码">
						<span class="focus-input100" data-symbol="&#xf190;"></span>
					</div>

					<div class="text-right p-t-8 p-b-31">
						<a href="javascript:">忘记密码？</a>
					</div>

					<div class="container-login100-form-btn">
						<div class="wrap-login100-form-btn">
							<div class="login100-form-bgbtn"></div>
							<button class="login100-form-btn">登 录</button>
						</div>
					</div>

					<div class="txt1 text-center p-t-54 p-b-20">
						<span>第三方登录</span>
					</div>

					<div class="flex-c-m">
						<a href="#" class="login100-social-item bg1">
							<i class="fa fa-wechat"></i>
						</a>

						<a href="#" class="login100-social-item bg2">
							<i class="fa fa-qq"></i>
						</a>

						<a href="#" class="login100-social-item bg3">
							<i class="fa fa-weibo"></i>
						</a>
					</div>

					<div class="flex-col-c p-t-25">
						<a href="javascript:" class="txt2">立即注册</a>
					</div>
				</form>
			</div>
		</div>
	</div>

	<script src="{% static 'login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'login/js/main.js' %}"></script>
</body>

</html>

templates/user/login2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.33,minimum-scale=1.0,maximum-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <title>会员登录</title>
    <meta http-equiv="Content-Language" content="zh-CN">
    <link rel="stylesheet" rev="stylesheet" href="//at.alicdn.com/t/font_2114244_d6n8x48t79b.css" type="text/css"
          media="all">
    <link rel="stylesheet" rev="stylesheet" href="{% static 'css/login_style.css' %}" type="text/css" media="all">
    <style>

    .tx-login-bg {
        background: url({% static 'images/bg.jpg' %}) no-repeat 0 0;
    }</style>
</head>
<body class="tx-login-bg">
<div class="tx-login-box">
    <div class="login-avatar bg-black"><i class="iconfont icon-user-fill"></i></div>
    <ul class="tx-form-li row">
        <li class="col-24 col-m-24">
            <p><input type="text" id="edtUserName" name="username" placeholder="Username"
                                              class="tx-input"><i>账号(*)</i></p></li>
        <li class="col-24 col-m-24">
            <p><input type="password" id="edtPassWord" name="password" placeholder="Password"
                                              class="tx-input"><i>密码(*)</i></p></li>
        <li class="col-24 col-m-24">
            <p class="tx-input-full">
                <button type="submit" id="loginbtnPost" name="loginbtnPost" class="tx-btn tx-btn-big bg-black">登录</button>
            </p>
        </li>
        <li class="col-12 col-m-12"><p><a href="{% url 'sskUser:register' %}" class="f-12 f-gray">新用户注册</a></p></li>
        <li class="col-12 col-m-12"><p class="ta-r"><a href="{% url 'sskUser:resetpwd' %}" class="f-12 f-gray">忘记密码</a></p></li>
    </ul>
</div>
</body>
</html>

templates/user/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width,initial-scale=1.33,minimum-scale=1.0,maximum-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <title>会员注册</title>
    <meta http-equiv="Content-Language" content="zh-CN">
    <link rel="stylesheet" rev="stylesheet" href="//at.alicdn.com/t/font_2114244_d6n8x48t79b.css" type="text/css"
          media="all">
    <link rel="stylesheet" rev="stylesheet" href="{% static 'css/login_style.css' %}" type="text/css" media="all">
    <style> .tx-login-bg {
        background: url({% static 'images/bg.jpg' %}) no-repeat 0 0;
    }</style>
</head>
<body class="tx-login-bg">
<div class="tx-login-box">
    <div class="login-avatar bg-black"><i class="iconfont icon-user"></i></div>
    <ul class="tx-form-li row">
        <form action="{% url 'sskUser:register' %}" method="post">
            {% csrf_token %}
        <li class="col-24 col-m-24">
            <p><input required="required" type="text" name="username" class="tx-input"><i>账号(*)</i>
        </p></li>
        <li class="col-24 col-m-24">
            <p><input required="required" type="password" name="password" class="tx-input"><i>密码(*)</i>
        </p></li>
        <li class="col-24 col-m-24">
            <p><input required="required" type="password" name="password2" class="tx-input"><i>确认密码(*)</i>
        </p></li>
        <!--li class="col-24 col-m-24"><p><input type="text" name="email" class="tx-input"><i>邮箱(*)</i></p></li -->
        <li class="col-24 col-m-24">
            <p class="input-ma">
                <input required="required" type="text" name="verifycode" class="tx-input" placeholder="验证码" />
            <img id="reg_verfiycode" style="border:none;vertical-align:middle;width:90px;height:30px;cursor:pointer;"
                 src="{% url 'sskUser:img_captcha' %}" alt="" title=""/></p></li>
        <li class="col-24 col-m-24">
            <p class="tx-input-full">
            <input type="submit" value="提交" class="tx-btn tx-btn-big bg-black" />
            </p>
        </li>
        </form>
        <li class="col-12 col-m-12">
            <p class="f-12 f-gray">已有账户？<a href="{% url 'sskUser:login' %}">去登陆</a></p>
        </li>
        <li class="col-12 col-m-12">
            <p class="ta-r"><a href="{% url 'sskUser:resetpwd' %}" class="f-12 f-gray">忘记密码</a></p>
        </li>
    </ul>
</div>
</body>
</html>

templates/user/resetpwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>找回密码</title>
</head>
<body>
<h1>TODO</h1>
</body>
</html>